on:
  push:
    branches:
      - 'db/*'
jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: dolthub/dolt
          event-type: release-dolt
          client-payload: '{"version": "fake-version-1.0.0", "actor": "${{ github.actor }}"}'
