on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  testing-commits-from-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("github.context.issue.pull_request:", context.issue.pull_request);
            console.log("github.context:", context);
